version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: backend_diego
    ports:
      - 8080:80
    volumes:
     - ./www/:/var/www/html
    depends_on:
      - database
    networks:
      app_network:
        aliases:
          - backend_host

  database:
    build:
      context: .
      dockerfile: mariadb.dockerfile
    container_name: mariadv_diego
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "logindb"
      MYSQL_ROOT_PASSWORD: "Diego.2020"
      MYSQL_ALLOW_EMPTY_PASSWROD: "true"
    volumes:
     - ./schemas/:/var/lib/logindb
    networks:
      app_network:
        aliases:
          - mariadb_host

volumes:
  www: {}
  schemas: {}

networks:
  app_network:
    name: app_net
    driver: bridge
    ipam:
      driver: default
 